// Mock for lucide-react
module.exports = {
  Plus: () => 'Plus',
  Minus: () => 'Minus',
  ChevronLeft: () => 'ChevronLeft',
  ChevronRight: () => 'ChevronRight',
  ChevronsLeft: () => 'ChevronsLeft',
  ChevronsRight: () => 'ChevronsRight',
  Ellipsis: () => 'Ellipsis',
  X: () => 'X',
  Menu: () => 'Menu',
  GripVertical: () => 'GripVertical',
  CircleAlert: () => 'CircleAlert',
  Lock: () => 'Lock',
  ArrowLeft: () => 'ArrowLeft',
  ArrowRight: () => 'ArrowRight',
  LoaderCircle: () => 'LoaderCircle',
  FileType: () => 'FileType',
  Grid3x3: () => 'Grid3x3',
  RectangleVertical: () => 'RectangleVertical',
  RectangleHorizontal: () => 'RectangleHorizontal',
  Columns3: () => 'Columns3',
  ChevronDown: () => 'ChevronDown',
  AlignLeft: () => 'AlignLeft',
  AlignCenter: () => 'AlignCenter',
  AlignRight: () => 'AlignRight',
  Calculator: () => 'Calculator',
  Type: () => 'Type',
  Link2: () => 'Link2',
  HelpCircle: () => 'HelpCircle',
  Bold: () => 'Bold',
  Italic: () => 'Italic',
  Paintbrush: () => 'Paintbrush',
  ScanBarcode: () => 'ScanBarcode',
  // Add any other icons used in the codebase
};
